AppBundle\Entity\Apartment:
    type: entity
    table: apartments
    repositoryClass: AppBundle\Repository\ApartmentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        move_in_date:
            type: datetime
            nullable: true
        street:
            type: string
            length: '255'
        postCode:
            type: integer
            column: post_code
        town:
            type: string
            length: '100'
        country:
            type: string
            length: '100'
        email:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
