<?php

namespace AppBundle\Repository;

/**
 * ApartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartmentRepository extends \Doctrine\ORM\EntityRepository
{
}
