<?php

namespace AppBundle\Repository;

/**
 * ApartmentTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartmentTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
